% Run a few test simulations and compare results against golden

testfuncs = { ...
             @test_round_cavity, ...
             @test_round_cavity_matched, ...
             @test_thin_cavity, ...
             @test_thin_cavity_lossy, ...
             @test_dipole_antenna, ...
             @test_coupled_microstrip ...
};

startTime = tic;

for tf=testfuncs
    disp( [ 'Running ', func2str( tf{1} ) ] );
    tf{1}();
end

elapsedTime = toc( startTime );

disp( [ 'All done in ', num2str( elapsedTime ), ' sec.' ] );

